name = "hub-health"
main = "src/worker.ts"
compatibility_date = "2025-02-14"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hub-health"
database_id = "inservice_db"
