name = "hub-health"
compatibility_date = "2025-02-14"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hub-health"
database_id = "cd5b7d90-33ee-4e73-8576-954796378182"
